name: dashshomework
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: 2.8.0

dependencies:
  bloc: ^8.0.1
  equatable: ^2.0.3
  fake_async: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  gap: ^2.0.0
  http: ^0.13.4
  intl: ^0.17.0
  just_audio: ^0.9.18
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.17

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/images/audio_control/
  fonts:
    - family: NanumPenScript
      fonts:
        - asset: assets/fonts/NanumPenScript-Regular.ttf
          weight: 400

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
