name: Build & Release
on: push

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
      - uses: actions/upload-artifact@v2
        with:
          name: dashshomework-android
          path: |
            build/app/outputs/apk/release/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
  build_ios:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - uses: actions/upload-artifact@v2
        with:
          name: dashshomework-ios
          path: build/ios/iphoneos/Runner.app
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter 
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev tar
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build linux --release
      - run: tar -cvf dashshomework-linux.tar build/linux/x64/release/bundle/
      - uses: actions/upload-artifact@v2
        with:
          name: dashshomework-linux
          path: dashshomework-linux.tar
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter 
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - run: |
          cd build\windows\runner
          Compress-Archive -Path Release -DestinationPath dashshomework-windows.zip
      - uses: actions/upload-artifact@v2
        with:
          name: dashshomework-windows
          path: 'build\windows\runner\dashshomework-windows.zip'
  build_macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter 
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos --release
      - uses: actions/upload-artifact@v2
        with:
          name: dashshomework-macos
          path: build/macos/Build/Products/Release/dashshomework.app
  build_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter 
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build web
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
  release:
    runs-on: ubuntu-latest
    needs: [
       build_android,
       build_ios,
       build_linux,
       build_windows,
       build_macos,
       build_web
    ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: ./GH_ARTIFACTS
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y tar
      - run: tar -cvf dashshomework-macos.app.tar GH_ARTIFACTS/dashshomework-macos
      - run: tar -cvf dashshomework-ios.app.tar GH_ARTIFACTS/dashshomework-ios
      - uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: |
            GH_ARTIFACTS/**/dashshomework-linux.tar
            GH_ARTIFACTS/**/*.apk
            GH_ARTIFACTS/**/*.aab
            GH_ARTIFACTS/**/dashshomework-windows.zip
            dashshomework-*.app.tar
